### ISSUE TITLE
Variable suggestions for order description do not work configuration page

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop1.6#12]
### Expected behavior

I expect variables not to be translated for the current locale. They should be English.

### Actual behavior

Variables to be used in order descriptions are translated into Dutch. These variables do not work.

<img width="1597" alt="image" src="https://user-images.githubusercontent.com/17008327/184140197-fbe998a8-450f-48cc-b60c-c28fa129e3db.png">

### Steps to reproduce the behavior

1. Install PrestaShop
2. Import Dutch locale
3. Enable Dutch in backoffice
4. Install mollie
5. Go to configuration page and open a method

### Environment
* PrestaShop version: 1.6.1.24
* Mollie module version: 4.5.2
* PHP version: 7.1.32

**Comment by justelis22** [comment]
Hey there, @muyncky!

Thank you for raising this request!
We will overview everything, and get back to you!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there @muyncky!

Our team has fixed the issue, you will be able to see everything in the next release, which should be done around the middle of September.

If you have any other questions, let us know!

Best Regards,
Invertus Support team.
