### ISSUE TITLE
Link does not work in configuration page for methods

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop1.6#13]
### Expected behavior

I expect links to work in the backoffice configuration page.

### Actual behavior

Links are escaped and not clickable.

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/17008327/184140915-f4468397-a8c6-4a64-8233-5f81b131d723.png">

### Steps to reproduce the behavior

1. Install PrestaShop
2. Install mollie
3. go to config page, part of method options and open a method

### Environment

* PrestaShop version: 1.6.1.24
* Mollie module version: 4.5.2
* PHP version: 7.1.32

**Comment by justelis22** [comment]
Hey there, @muyncky!

Thank you for raising this request!
We will overview everything, and get back to you!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there @muyncky!

Our team has fixed the issue, you will be able to see everything in the next release, which should be done around the middle of September.

If you have any other questions, let us know!

Best Regards,
Invertus Support team.
