### ISSUE TITLE
Wikipedia link explaining locale does not work

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop1.6#14]
### Expected behavior

I expect links to work in the backoffice and not give unexpected behaviour in other parts of the configuration page.

### Actual behavior

Link tag is not closed, and affects another switch button:

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/17008327/184141445-1d3def5f-d71d-442b-aa71-a8e1077a460d.png">

### Steps to reproduce the behavior

1. Install PrestaShop
2. Install Mollie
3. Go the page advanced

### Environment

* PrestaShop version: 1.6.1.24
* Mollie module version: 4.5.2
* PHP version: 7.1.32

**Comment by justelis22** [comment]
Hey there, @muyncky!

Thank you for raising this request!
We will overview everything, and get back to you!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hello there @muyncky!

Our team has fixed the issue, you will be able to see everything in the next release, which should be done around the middle of September.

If you have any other questions, let us know!

Best Regards,
Invertus Support team.
