### ISSUE TITLE
Missing house number in Klarna; address2 is not passed to Order API

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop1.6#16]
### Expected behavior

When placing an order using the Order API, the address2 is not passed to the delivery address (in for example Klarna). Often this contains the house number. See this address:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/17008327/188848192-96951161-763e-46b1-8bd3-ffd2abddface.png">

The shipping addres, **does** contain the housenummer (`ps_address.address2`).

### Actual behavior

Pass `address2` from the delivery address to the Order API.

### Steps to reproduce the behavior

We cannot reproduce in testing mode. Maybe 

- Place a real order for Klarna
- Make sure the delivery address of the order has a value in both `address1` and `address2`.
- Checkout the order in Klarna

### Environment
* PrestaShop version: 1.6.1.24 
* Mollie module version: 4.5.2 
* PHP version: 7.2.32

**Comment by justelis22** [comment]
Hey there @muyncky,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by muyncky** [comment]
@justelis22 we have a possible fix for this. PR is coming later. Any special requirements for contributing?

**Comment by justelis22** [comment]
Hey @muyncky,

Thanks! We have checked the PR, it seems to be very nice, good job!
Forwarded this information to the Mollie team, we will communicate internally, and let you know how we can proceed!

Thank you for your patience!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey there @muyncky,

We have merged the PR, and it will be added to the new release of the module, but for now if you don't have it already, you can download it from the GitHub.

We will mark this issue as resolved, but if you have something else to add, don't hesitate to contact us!
By the way, thank again for the solution.

Best Regards,
Invertus Support team.
