### ISSUE TITLE
Payment with Klarna: Shipment information cannot be sent

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop1.6#22]
### Expected behavior

When a Klarna order is placed and authorized, I expect the order to be shipped after payment status is _Payment accepted_.

### Actual behavior

The order is not marked as shipped due to this error:

```
Log ID (634695c46ce5a) \| Shipment information cannot be sent. Order reference (TNDQYRUIR) has no payment information. . context: []
```

#### Settings

**General settings**
![image](https://user-images.githubusercontent.com/17008327/195320342-987a631f-c8de-4937-a810-32c3ada93368.png)

**Advanced settings**

![image](https://user-images.githubusercontent.com/17008327/195320480-b104be17-ba5f-40a2-b3f2-77c87b74d947.png)

**Full log**

```
9 | -- | 1 | Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart | Cart | 6 | 0x 0 | 10/12/2022 10:24:06
-- | -- | -- | -- | -- | -- | -- | --
8 | -- | 1 | Mollie\\Service\\TransactionService::processTransaction said: Received webhook request for order 6 / transaction ord_yplipu |   | 0 | 0x 0 | 10/12/2022 10:24:06
7 | -- | 2 | Log ID (634695c46ce5a) \| Shipment information cannot be sent. Order reference (TNDQYRUIR) has no payment information. . context: [] |   | 0 | 0x 0 | 10/12/2022 10:24:04
6 | -- | 1 | Mollie incoming webhook: id=ord_yplipu |   | 0 | 0x 0 | 10/12/2022 10:24:03
```

**Order**

![image](https://user-images.githubusercontent.com/17008327/195321940-247645a0-4b25-4179-b66d-6041f7976b0a.png)

### Steps to reproduce the behavior

* Install PrestaShop 1.6.1.24
* Install Mollie [v4.5.3](https://github.com/mollie/PrestaShop1.6/releases/tag/v4.5.3) by downloading and uploading via backoffice
* Add a test key and use the settings described in the images above. What is important here: _Automatically ship when one of these statuses is reached:_ and select _Payment accepted_
* Place an order through the frontoffice similar to shown above 

### Environment
* PrestaShop version: 1.6.1.24
* Mollie module version: [v4.5.3](https://github.com/mollie/PrestaShop1.6/releases/tag/v4.5.3)
* PHP version: 7.1.33

**Comment by justelis22** [comment]
Hi there @muyncky,

Thank you for the detailed request. 
We will check and get back to you with an update!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @muyncky,

We have communicated with the Mollie team and decided not to do this improvement on the 1.6 PrestaShop version.

Although this issue was already fixed on the module created for PrestaShop 1.7, so we encourage you to migrate to the newer version.

If you have some additional questions, let us know, for now, we are going to close the issue!

Best Regards,
Invertus Support team.

**Comment by muyncky** [comment]
Thanks @justelis22 for getting back.

Can you point me to the PR that solves this in the ps17 project? That would help us a lot!

**Comment by justelis22** [comment]
Hi @muyncky,

Sure, here is the PR - https://github.com/Invertus/mollie1.7/pull/340

If you have any questions, let us know!

Best Regards,
Invertus Support team.
