### ISSUE TITLE
No payment options - Prestashop Mollie module

### ISSUE THREAD

**Issue by Carindesign** [mollie/PrestaShop1.6#30]
### Expected behavior
Show payment method

### Actual behavior
No payment options are shown, Mollie does not appear. After upgrading from Prestashop 8.0.5 to Prestashop 8.1.2

### Steps to reproduce the behavior
After the order steps during the checkout no payment options shows up

### Environment
* PrestaShop version: 8.1.2 
* Mollie module version: 6.0.4 
* PHP version: 8.1.25 

See printscreens. How can I fix it?

![Scherm­afbeelding 2023-12-12 om 11 13 58](https://github.com/mollie/PrestaShop1.6/assets/58775883/727d0f8f-b2dc-4dea-96b0-da1ee3d0dbf1)

![Scherm­afbeelding 2023-12-12 om 11 12 12](https://github.com/mollie/PrestaShop1.6/assets/58775883/5642938a-e573-4236-a192-0b4b0db53502)

![Scherm­afbeelding 2023-12-12 om 11 11 48](https://github.com/mollie/PrestaShop1.6/assets/58775883/7364d048-4f89-4339-9965-a992dea3b1e4)

![Scherm­afbeelding 2023-12-12 om 11 09 43](https://github.com/mollie/PrestaShop1.6/assets/58775883/1040b9c3-5efd-419e-888a-621907f7ebfa)

**Comment by justelis22** [comment]
Hi there @Carindesign,

Most likely the issue is related to the upgrade, something could have been corrupted. 
Could you please try to reset the Mollie module to see if the issue is fixed?

Keep in mind that all of the module data will be set to default states.

I will be waiting for your update!

Best Regards,
Invertus Support team.

**Comment by Carindesign** [comment]
@justelis22
Thank you for your answer.

I have also reset de Mollie module.

Best regards

**Comment by justelis22** [comment]
Hi there @Carindesign,

Could you please share the shop access? We would need FTP and back-office credentials.
Share the credentials with our email support@invertus.eu.

Waiting for your answer!

Best Regards,
Invertus Support team.

**Comment by Carindesign** [comment]
Hi @justelis22,
I have send you an email.
Best regards,

**Comment by Carindesign** [comment]
Hi @justelis22 
Do you have seen the email?
Best regards

**Comment by justelis22** [comment]
Hi there @Carindesign,

We have not received an email from you. Could you please retry sending the information?

Waiting for your update!

Best Regards,
Invertus Support team.

**Comment by Carindesign** [comment]
Hi @justelis22 
I have sent a new email from the email address info@carindesign.nl
Best regards,

**Comment by justelis22** [comment]
@Carindesign,

I have not received an email from that address, but wrote you an email to info@carindesign.nl.

Best Regards,
Invertus Support team.
